version: '3'
services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://scratchpay:scratchpay@db:5432/scratchpay
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/   
    expose:
      - 5432
    environment:
      - POSTGRES_USER=scratchpay
      - POSTGRES_PASSWORD=scratchpay
      - POSTGRES_DB=scratchpay

volumes:
  postgres_data:
#      driver: local